### ISSUE TITLE
Trakt watched crash with EXC_BAD_INSTRUCTION

### ISSUE THREAD

**Issue by mecid** [arsonik/AKTrakt#6]
Query method crashes with EXC_BAD_INSTRUCTION after update to 0.3

**Comment by arsonik** [comment]
Hmm try Product clean / clean build folder

**Comment by mecid** [comment]
@arsonik not helped.

![2016-05-20 9 11 25](https://cloud.githubusercontent.com/assets/324372/15417830/f0c7347a-1e6a-11e6-98a4-0b7ea50fe35c.png)

**Comment by arsonik** [comment]
how did you call the recommendations method ?
cause I remember changing the parameters a while back.
and the error you gets I can't reproduce it

**Comment by mecid** [comment]
@arsonik working now, after reinstalling the app.
