### ISSUE TITLE
Empty seasons in TraktShow.

### ISSUE THREAD

**Issue by mecid** [arsonik/AKTrakt#8]
I get empty seasons in TraktShow when use
`TraktRequestGetWatched(type: .Shows, extended: [TraktRequestExtendedOptions.Full, .Images, .Episodes])`

How i can include to result of this request information about watched episodes?

**Comment by arsonik** [comment]
Sorry about that, I just fixed it !
If you are using cocoapods and want the latest version use 
`pod "AKTrakt", :git => "https://github.com/arsonik/AKTrakt.git"`
Cause i'm not pushing a new pod version everytime I add/fix something
Cheers

**Comment by mecid** [comment]
@arsonik thanks)
