### ISSUE TITLE
TraktShow notCompleted always return all Episodes.

### ISSUE THREAD

**Issue by mecid** [arsonik/AKTrakt#9]
I am using TraktRequestGetWatched for getting watched shows. Show property notCompleted always return all episodes. How can i fix this problem to get unwatched episodes?

**Comment by arsonik** [comment]
Ok I've changed the way it return the notCompleted list.
When you request TraktRequestGetWatched (aka /sync/watched/shows) you'll only get episodes you've watched so notCompleted should now be empty.
If You want the progress for a show use TraktRequestShowProgress instead, then you should have notCompleted filled with correct episodes

**Comment by mecid** [comment]
@arsonik Any chance to get list of watched shows with next unwatched episode, without doing multiple requests?

**Comment by arsonik** [comment]
I can definitely do a new request that call these two separate webservices, cause trakt api doesn't provide an endpoint to aggregate these :(

**Comment by arsonik** [comment]
@mecid The only downside of it, is that it's gonna to take a while to call the completion closure, if you have a lot of watched shows ! 
Let's say you're watching 20 shows, you'll have to wait for the first request (show/watched) + another 20 requests (one for each show/progress)!

**Comment by mecid** [comment]
@arsonik I need to show list of Shows with Next Episide information.

**Comment by arsonik** [comment]
Here is what i do :

```
        TraktRequestGetWatched(type: TraktShow.self, extended: .Images).request(trakt) { [weak self] results, error in
            results?.forEach { show in
                guard let ss = self else {
                    return
                }
                TraktRequestShowProgress(showId: show.id, extended: [.Full, .Images]).request(ss.trakt) { [weak self] seasons, error -> Void in
                    show.seasons = seasons ?? show.seasons
                    guard show.nextEpisode != nil else {
                        return
                    }

```
